# Generated by Django 3.1.7 on 2021-03-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('year', models.CharField(blank=True, default='', max_length=50, verbose_name='Год(ы)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.poet', verbose_name='Автор(ша)')),
            ],
            options={
                'verbose_name': 'Стихотворение',
                'ordering': ('title',),
            },
        ),
    ]
